### ISSUE TITLE
Backport Request

### ISSUE THREAD

**Issue by ghost** [Smootheez/Elytra-Control#1]
Thank you for a very nice mod.

If you feel like it, please consider backporting to 1.20.1.

**Comment by Smootheez** [comment]
I've consider about it, for now it's better for me to just focus creating a new feature for newest Minecraft instead of creating backport version.  Version 0.1.4 is the last version for Minecraft 1.20.4-.1.20.6, it won't receive any feature update. The newest feature is only for the newest Minecraft.

**Comment by ghost** [comment]
Okay, I will respect your wishes.
